name: eshop
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0
  esys_flutter_share: ^1.0.2
  http: ^0.12.2
  shared_preferences: ^0.5.12
  connectivity: 2.0.2
  jaguar_jwt: ^2.1.6
  flutter_local_notifications: 3.0.2
  path_provider: 1.6.18
  firebase_messaging: 7.0.3
  cached_network_image: ^2.5.0
  flutter_rating_bar: 3.2.0+1
  flutter_html: 1.2.0
  photo_view: 0.9.2
  flutter_webview_plugin: 0.3.11
  firebase_auth: ^0.18.4+1
  sms_autofill: ^1.3.0
  intl: 0.16.1
  country_code_picker: 1.6.0
  google_maps_flutter: 1.0.6
  geolocator: ^6.1.13
  location: 3.0.2
  file_picker: ^2.1.4
  shimmer: 1.1.2
  geocoding: 1.0.5
  razorpay_flutter: 1.2.3
  curved_navigation_bar: 0.3.7
  flutter_paystack: ^1.0.4+1
  flutter_html_to_pdf: ^0.5.2
  permission_handler: ^5.0.1+1
  in_app_review: ^1.0.0
  firebase_dynamic_links: ^0.6.3
  open_file: ^3.0.3
  provider: ^4.3.2+4
  stripe_payment: ^1.0.9
  video_player: ^1.0.1
  flutter_svg: ^0.19.0
  paytm: ^2.0.0
  youtube_player_flutter: ^7.0.0+7
  downloads_path_provider_28:
     path: ./downloads_path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
      sdk: flutter


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/Language/



  fonts:
    - family: opensans
      fonts:
        - asset: assets/font/OpenSans-Regular.ttf
